package ice.ui.bundle

import ice.content.*
import ice.library.type.meta.stat.IceStatCats
import ice.library.type.meta.stat.IceStats

object ZNCH : BaseBundle() {
    init {
        unlockableContent.apply {
            put(IceBlocks.肿瘤地,arrayOf("肿瘤地"))
            put(IceBlocks.跨界钢板墙,arrayOf("跨界钢板墙"))
            put(IceBlocks.肿瘤墙,arrayOf("肿瘤墙"))
            put(IceBlocks.肉瘤菇,arrayOf("肉瘤菇"))
            put(IceBlocks.肿瘤井,arrayOf("肿瘤井"))
            put(IceBlocks.肿瘤喷口,arrayOf("肿瘤喷口"))
            put(IceBlocks.神矢,arrayOf("神矢"))
            put(IceBlocks.新月岩, arrayOf("新月岩"))
            put(IceBlocks.新月喷口, arrayOf("新月喷口"))
            put(IceBlocks.新月岩墙, arrayOf("新月岩墙"))
            put(IceBlocks.铬墙, arrayOf("铬墙"))
            put(IceBlocks.大型铬墙, arrayOf("大型铬墙"))
            put(IceBlocks.巨型铬墙, arrayOf("巨型铬墙"))
            put(IceBlocks.软红冰, arrayOf("软红冰"))
            put(IceBlocks.绿羽墙, arrayOf("绿羽墙"))
            put(IceBlocks.绿羽地, arrayOf("绿羽地"))
            put(IceBlocks.灰烬地, arrayOf("灰烬地"))
            put(IceBlocks.灰烬墙,arrayOf("灰烬墙"))
            put(IceBlocks.幽灵草, arrayOf("幽灵草"))
            put(IceBlocks.幽灵草墙, arrayOf("幽灵草墙"))
            put(IceBlocks.多叶草, arrayOf("多叶草"))
            put(IceBlocks.霜寒草, arrayOf("霜寒草"))
            put(IceBlocks.地笼草, arrayOf("地笼草"))
            put(IceBlocks.枯棕枝, arrayOf("枯棕枝"))
            put(IceBlocks.绿羽, arrayOf("绿羽"))
            put(IceBlocks.绯叶绮, arrayOf("绯叶绮"))
            put(IceBlocks.草嫣红, arrayOf("草嫣红"))
            put(IceBlocks.叶嫣粉, arrayOf("叶嫣粉"))
            put(IceBlocks.风蚀喷口,arrayOf("风蚀喷口"))
            put(IceBlocks.潮汐喷口,arrayOf("潮汐喷口"))
            put(IceBlocks.钢铁墙, arrayOf("钢铁墙"))
            put(IceBlocks.钢铁地板, arrayOf("钢铁地板"))
            put(IceBlocks.钢铁地板1, arrayOf("钢铁地板1"))
            put(IceBlocks.红冰石, arrayOf("红冰石"))
            put(IceBlocks.红土墙, arrayOf("红土墙"))
            put(IceBlocks.红土, arrayOf("红土"))
            put(IceBlocks.侵蚀层地墙, arrayOf("侵蚀层地墙"))
            put(IceBlocks.侵蚀层地, arrayOf("侵蚀层地"))
            put(IceBlocks.潮汐石, arrayOf("潮汐石"))
            /**方块类*/
            put(IceBlocks.基础传送带, arrayOf("基础传送带"))
            put(IceBlocks.真菌塔, arrayOf("真菌塔"))
            put(IceBlocks.血肉枢纽, arrayOf("血肉枢纽"))
            put(IceBlocks.碎冰, arrayOf("碎冰"))
            put(IceBlocks.潮汐石墙, arrayOf("潮汐石墙"))
            put(IceBlocks.流纹岩, arrayOf("流纹岩"))
            put(IceBlocks.流纹岩墙, arrayOf("流纹岩墙"))
            put(IceBlocks.云英岩, arrayOf("云英岩"))
            put(IceBlocks.云英岩墙, arrayOf("云英岩墙"))
            put(IceBlocks.幽灵簇, arrayOf("幽灵簇"))
            put(IceBlocks.风蚀砂地, arrayOf("风蚀砂地"))
            put(IceBlocks.光辉板岩, arrayOf("光辉板岩"))
            put(IceBlocks.光辉板岩墙, arrayOf("光辉板岩墙"))
            put(IceBlocks.风蚀沙地, arrayOf("风蚀沙地"))
            put(IceBlocks.风蚀沙墙, arrayOf("风蚀沙墙"))
            put(IceBlocks.利芽, arrayOf("利芽"))
            put(IceBlocks.血浅滩, arrayOf("血浅滩"))
            put(IceBlocks.血池, arrayOf("血池"))
            put(IceBlocks.红冰, arrayOf("红冰"))
            put(IceBlocks.红冰墙, arrayOf("红冰墙"))
            put(IceBlocks.金珀沙, arrayOf("金珀沙"))
            put(IceBlocks.金珀沙墙, arrayOf("金珀沙墙"))
            put(IceBlocks.深血池, arrayOf("深血池"))
            put(IceBlocks.灵液池, arrayOf("灵液池"))
            put(IceBlocks.皎月银沙, arrayOf("皎月银沙"))
            put(IceBlocks.皎月银沙墙, arrayOf("皎月银沙墙"))
            put(IceBlocks.潮汐水石, arrayOf("潮汐水石"))
            put(IceBlocks.殷红树, arrayOf("殷红树"))
            put(IceBlocks.血晶尖刺, arrayOf("血晶尖刺"))
            put(IceBlocks.血孢子丛, arrayOf("血孢子丛"))
            put(IceBlocks.风蚀沙柱, arrayOf("风蚀沙柱"))
            put(IceBlocks.跨界钢板, arrayOf("跨界钢板"))
            put(IceBlocks.大风蚀沙柱, arrayOf("大风蚀沙柱"))
            put(IceBlocks.基础实验室, arrayOf("基础实验室"))
            put(IceBlocks.遗弃匣, arrayOf("遗弃匣"))
            put(IceBlocks.量子蚀刻厂,
                arrayOf("量子蚀刻厂", "采用等离子蚀刻技术,在硅晶圆上雕刻出微米级电路,电子工业的基础设施"))
            put(IceBlocks.蜂巢陶瓷合成巢, arrayOf("蜂巢陶瓷合成巢",
                "利用基因改造的硅基菌群分泌陶瓷基质,再经激光固化,生产过程中会发出蜂鸣般的共振声", "资源蜜蜂?"))
            put(IceBlocks.碳控熔炉, arrayOf("碳控熔炉",
                "通过精确控制碳元素配比,在同一生产线灵活产出高碳钢和低碳钢,稳定的温度控制确保钢材质量始终达标"))
            put(IceBlocks.碳钢墙1, arrayOf("碳钢墙"))
            put(IceBlocks.碳钢墙2, arrayOf("大型碳钢墙"))
            put(IceBlocks.云英石柱, arrayOf("云英石柱"))
            put(IceBlocks.铸铜厂, arrayOf("铸铜厂"))
            put(IceBlocks.流体枢纽, arrayOf("流体枢纽"))
            put(IceBlocks.液体抽离器, arrayOf("液体抽离器"))
            put(IceBlocks.无人机供货端, arrayOf("无人机供货端"))
            put(IceBlocks.无人机需求端, arrayOf("无人机需求端"))
            put(IceBlocks.遗弃资源箱, arrayOf("遗弃资源箱"))
            put(IceBlocks.定向超速器, arrayOf("定向超速器"))
            put(IceBlocks.转化分类器, arrayOf("转化分类器", "通过配置调整分类状态"))
            put(IceBlocks.梯度传送带, arrayOf("梯度传送带"))
            put(IceBlocks.基础路由器, arrayOf("基础路由器"))
            put(IceBlocks.传输节点, arrayOf("传输节点"))
            put(IceBlocks.转化溢流门, arrayOf("转化溢流门", "通过配置调整溢流状态"))
            put(IceBlocks.钴熠传送带, arrayOf("钴熠传送带"))
            put(IceBlocks.传输矿仓, arrayOf("传输矿仓"))
            put(IceBlocks.曼哈德钻井, arrayOf("曼哈德钻井"))
            put(IceBlocks.蛮荒钻井, arrayOf("蛮荒钻井"))
            put(IceBlocks.纤汲钻井, arrayOf("纤汲钻井"))
            put(IceBlocks.随机源, arrayOf("随机源", "随机输出所有资源"))
            put(IceBlocks.量子卸载器,
                arrayOf("量子卸载器", "通过量子相干效应实现零损耗电子迁移,像虹吸液体般优雅地转移高密度数据流"))
            put(IceBlocks.单晶硅厂, arrayOf("单晶硅厂", "使用硫化物和石英矿石生产纯度更高的单晶硅"))
            /**物品类*/
            put(IceItems.钴锭, arrayOf("钴锭", "良好的耐高温,耐腐蚀是它成为建材的重要原因,很多测量仪器都要用到它"))
            put(IceItems.晶状孢芽, arrayOf("晶状孢芽"))
            put(IceItems.灼热孢团, arrayOf("灼热孢团"))
            put(IceItems.寂温疮体, arrayOf("寂温疮体"))
            put(IceItems.复合陶瓷, arrayOf("复合陶瓷",
                "凭借其超凡的抗冲击性和热稳定性,既能作为能量护盾发生器的核心基底材料,又能制成高速单位的防热瓦"))
            put(IceItems.铪锭, arrayOf("铪锭", "这种稀缺的材料对所有和能量有关的建筑都很重要"))
            put(IceItems.锆英石, arrayOf("锆英石", "用于耐火材料,此外也用于金属合金"))
            put(IceItems.硫钴矿, arrayOf("硫钴矿", "银白色金属光泽,常带粉红色调,立方体或八面体晶形",
                "这玩意儿比钻石难啃\n——采矿队长R-42的日志"))
            put(IceItems.红冰, arrayOf("红冰"))
            put(IceItems.骨钢, arrayOf("骨钢"))
            put(IceItems.黄玉髓, arrayOf("黄玉髓"))
            put(IceItems.金珀沙, arrayOf("金珀沙"))
            put(IceItems.铬铁矿, arrayOf("铬铁矿", "主要用来生产金属铬"))
            put(IceItems.血囊孢子, arrayOf("血囊孢子",
                "殷红树上采集的一种孢子,一般为殷红树单胞繁殖体,生物结构非常不稳定,也可能分化成[red]其他植株[]"))
            put(IceItems.无名肉块, arrayOf("无名肉块", "", "我们以为北极只是冷,现在才知道,寒冷也能如此饥饿"))
            put(IceItems.碎骨, arrayOf("碎骨"))
            put(IceItems.肌腱, arrayOf("肌腱"))
            put(IcePlanets.伊甸,arrayOf("伊甸"))
            put(IceItems.脊髓末梢, arrayOf("脊髓末梢"))
            put(IceItems.生煤, arrayOf("生煤", "未被加工的粗质煤矿"))
            put(IceItems.燃素水晶,arrayOf("燃素水晶"))
            put(IceItems.石英, arrayOf("石英", "高硬度晶体,主要成分为SiO₂,对于极端酸性环境有优异的耐受性"))
            put(IceItems.精制煤, arrayOf("精制煤", "脱硫精炼后的煤,作为燃料或作进一步加工之用"))
            put(IceItems.低碳钢, arrayOf("低碳钢"))
            put(IceItems.高碳钢, arrayOf("高碳钢", "碳含量的增加使其比低碳钢更为坚硬,代价则是韧性与热硬性的损失"))
            put(IceItems.铜锭, arrayOf("铜锭", "这种金属以及为优秀的导电性和导热性著称"))
            put(IceItems.铅锭, arrayOf("铅锭", "超高密度和卓越的辐射屏蔽能力,完美诠释了攻防一体",
                "从挡住辐射到砸穿装甲,这份量从来不会让人失望"))
            put(IceItems.锌锭, arrayOf("锌锭",
                "其独特的牺牲阳极保护和加热后的超塑性,既能作为装甲镀层大幅延长载具寿命,又可制成高能锌空气电池为单位护盾供电",
                "防锈?试试用锌箔包裹EMP炸弹:)"))
            put(IceItems.金矿, arrayOf("金矿", "主要用于提炼黄金"))
            put(IceItems.金锭, arrayOf("金锭", "一种贵重金属,可以用来制作电子部件"))
            put(IceItems.赤铁矿, arrayOf("赤铁矿", "地表常见矿物,用于合成碳素钢"))
            put(IceItems.方铅矿, arrayOf("方铅矿", "方铅矿是提取铅的主要矿物来源,形态常为细粒至粗粒的块状或粒状集合体"))
            put(IceItems.黄铜锭, arrayOf("黄铜锭", "一种铜合金,有较高的强度和耐腐蚀性,适用于制造各种结构零和连接件"))
            put(IceItems.黄铜矿, arrayOf("黄铜矿", "铜铁硫化物矿石,含有微量金,银"))
            put(IceItems.闪锌矿, arrayOf("闪锌矿",
                "闪锌矿是提炼锌的最重要矿物原料,纯闪锌矿近于无色,但通常因含铁而呈浅黄,浅绿,随含铁量的增加而变深"))
            put(IceItems.单晶硅, arrayOf("单晶硅", "信息工业的基石,需要进一步加工增强其半导体性能"))
            put(IceItems.石英玻璃,
                arrayOf("石英玻璃", "耐高温,低膨胀系数,有效抵御大部分化学反应,是理想的化学反应容器材料"))
            put(IceItems.石墨烯, arrayOf("石墨烯", "高度有序的单层碳原子材料", ""))
            put(IceItems.电子元件, arrayOf("电子元件"))
            /**液体类*/
            put(IceLiquids.浓稠血浆, arrayOf("浓稠血浆", "从朔方蔓延而来"))
            put(IceLiquids.沼气, arrayOf("沼气", "主要成分是甲烷,可以替代部分工厂的燃料需求"))
            put(IceLiquids.灵液, arrayOf("灵液", "一种酸性极强的溶液,可以用来处理金属"))
            put(IceLiquids.氦气, arrayOf("氦气", "虽然不可燃烧,但是处理之后依旧可形成高能燃料"))
            /**状态类*/
            put(IceStatus.维生II,
                arrayOf("维生II", "激活纳米机器人集群,将储存的硅矿微粒与裂解液转化为生物修复单元,持续重构受损机体"))
            put(IceStatus.维生I,
                arrayOf("维生I", "激活纳米机器人集群,将储存的硅矿微粒与裂解液转化为生物修复单元,持续重构受损机体"))
            put(IceStatus.融合, arrayOf("融合", "当血肉单位满足特定条件时,融合状态触发,逐渐靠近结合,属性整合提升"))
            put(IceStatus.电磁脉冲, arrayOf("电磁脉冲", "突发宽带电磁辐射的高强度脉冲,用于破坏敌人的电子设备"))
            put(IceStatus.流血, arrayOf("流血"))
            put(IceStatus.回响, arrayOf("回响"))
            put(IceStatus.搏动, arrayOf("剧烈搏动"))
            put(IceStatus.破甲I, arrayOf("破甲I", "目标单位护甲扣除,使其遭受的伤害显著提升"))
            put(IceStatus.破甲II, arrayOf("破甲II", "目标单位护甲扣除,使其遭受的伤害显著提升"))
            put(IceStatus.破甲III, arrayOf("破甲III", "目标单位护甲扣除,使其遭受的伤害显著提升"))
            put(IceStatus.穿甲, arrayOf("穿甲", "完全无视目标护甲,直接穿透对本体造成伤害"))
            put(IceStatus.寄生, arrayOf("寄生", "寄生状态会逐渐消耗单位生命值致其死亡,随后生成血肉单位"))
            put(IceStatus.集群,
                arrayOf("集群", "激活协同协议,单位间建立纳米机器人共享网络,效应随范围内友方单位数量增强"))
            put(IceStatus.邪火, arrayOf("邪火", "持续生命侵蚀,扣除单位生命上限"))
            put(IceStatus.圣火, arrayOf("圣火", "持续造成目标最大生命值百分比的火焰伤害"))
            /**单位类*/
            put(IceUnitTypes.路西法, arrayOf("路西法"))
            put(IceUnitTypes.仆从, arrayOf("仆从",
                "作为传教者的专属防空护卫,仆从搭载了双联装净化之焰喷射器,能够喷射高温圣焰,专门克制无人机集群",
                "确定是护卫不是火刑柱?"))
            put(IceUnitTypes.传教者, arrayOf("传教者",
                "重型空中火力平台,枢机教廷[净化之翼]军团,搭载4门防空拦截的磁轨速射炮,2门圣裁等离子爆裂炮,以及2门对地穿甲的粒子冲击炮形成全方位立体火力网",
                "谓天罚,不过是枢机的例行祷告"))
            put(IceUnitTypes.裂片集群, arrayOf("裂片集群"))
            put(IceUnitTypes.断业, arrayOf("断业",
                "断业是神殿[净罪计划]的产物,其装甲内层熔铸了经神祝圣的净化合金,主炮对建筑与重甲单位造成毁灭性伤害,能撕裂红雾中的畸变体集群,弹头内藏的圣水可延缓红雾生物再生",
                "帝国腐朽的装甲部队节节败退,唯有枢机的神术能短暂驱散腐化,帝国残部讥讽其为[伪神的铁棺材],但无人能否认——当它的履带碾过焦土时,连红雾都会为之退散"))
            /**行星类*/
            put(IcePlanets.阿德里, arrayOf("阿德里"))
        }
        stat.apply {
            // 统计属性类
            put(IceStats.生产进度, "生产进度")
            put(IceStats.单位数量, "单位数量")
            put(IceStats.破甲, "破甲")
            put(IceStats.可连接建筑, "可连接建筑")
            put(IceStats.最大连接, "最大连接")
            put(IceStats.状态重载时间, "状态重载时间")
            put(IceStats.状态效果, "状态效果")
            put(IceStats.状态持续时间, "状态持续时间")
            put(IceStats.范围, "范围")
            put(IceStats.营养浓度, "营养浓度")
            put(IceStats.建造时间花费, "建造时间花费")
            put(IceStats.建筑血量系数, "建筑血量系数")
            put(IceStats.硬度, "硬度")
            put(IceStats.是否用于建造, "是否用于建造")
            put(IceStats.配方, "配方")
            put(IceStats.返回, "返回")
            put(IceStats.鸣谢, "鸣谢")
            put(IceStats.关闭, "关闭")
            put(IceStats.进度, "进度")
            put(IceStats.科技, "科技")
            put(IceStats.数据, "数据")
            put(IceStats.成就, "成就")
            put(IceStats.检验, "检验")
            put(IceStats.设置, "设置")
            put(IceStats.日志, "日志")
            put(IceStats.数据库, "数据库")
            put(IceStats.蓝图, "蓝图")
            put(IceStats.研究, "研究")
            put(IceStats.星球, "星球")
            put(IceStats.深空, "DeepSpace")
            put(IceStats.地板, "地板")
            put(IceStats.详情, "详情")
            put(IceStats.连接, "连接 {0}/{1}")
        }
        statCat.apply {
            put(IceStatCats.deepSpace, "deepSpace")
        }
    }
}