name: Gradle Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Build Tools
        run: sdkmanager "build-tools;37.0.0-rc2"





      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.4.1

      - name: Make gradlew executable
        run: chmod +x ./gradlew




      - name: Build JAR
        run: ./gradlew deployVersion
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Extract Version
        id: version
        run: |
          VERSION=$(grep -oP '"version"\s*:\s*"\K[^"]+' mod.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DeepSpace-${{ steps.version.outputs.version }}
          path: build/libs/version/DeepSpace-Alpha-*.jar

      - name: Release Nightly
        uses: ncipollo/release-action@v1
        with:
          tag: nightly
          name: Nightly (${{ steps.version.outputs.version }})
          body: |
            自动构建：**${{ steps.version.outputs.version }}**
            提交：${{ github.sha }}
          artifacts: build/libs/version/DeepSpace-Alpha-*.jar
          allowUpdates: true
          removeArtifacts: true
          prerelease: false
          makeLatest: true
          token: ${{ secrets.RELEASE_TOKEN }}

